-- Table de nomenclature PCS-ESE (Professions et Catégories Socioprofessionnelles - Employés Salariés d'Entreprises)
CREATE TABLE IF NOT EXISTS nomenclature_pcs_ese (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    code VARCHAR(10) NOT NULL UNIQUE,  -- Ex: 231a, 311c, 382a
    libelle VARCHAR(500) NOT NULL,
    categorie_principale INTEGER NOT NULL,  -- 1,2,3,4,5,6 (premier chiffre du code)
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Index pour recherche rapide par code
CREATE INDEX IF NOT EXISTS idx_pcs_ese_code ON nomenclature_pcs_ese(code);
CREATE INDEX IF NOT EXISTS idx_pcs_ese_categorie ON nomenclature_pcs_ese(categorie_principale);

-- Insertion des données de la nomenclature PCS-ESE
-- 1 AGRICULTEURS
INSERT INTO nomenclature_pcs_ese (code, libelle, categorie_principale) VALUES
('100x', 'Agriculteurs et éleveurs, salariés de leur exploitation', 1);

-- 2 ARTISANS, COMMERCANTS ET CHEFS D'ENTREPRISES
INSERT INTO nomenclature_pcs_ese (code, libelle, categorie_principale) VALUES
('210x', 'Artisans salariés de leur entreprise', 2),
('220x', 'Commerçants et assimilés, salariés de leur entreprise', 2),
('231a', 'Chefs de grande entreprise de 500 salariés et plus', 2),
('232a', 'Chefs de moyenne entreprise, de 50 à 499 salariés', 2),
('233a', 'Chefs d''entreprise du bâtiment et des travaux publics, de 10 à 49 salariés', 2),
('233b', 'Chefs d''entreprise de l''industrie ou des transports, de 10 à 49 salariés', 2),
('233c', 'Chefs d''entreprise commerciale, de 10 à 49 salariés', 2),
('233d', 'Chefs d''entreprise de services, de 10 à 49 salariés', 2);

-- 3 CADRES ET PROFESSIONS INTELLECTUELLES SUPERIEURES
INSERT INTO nomenclature_pcs_ese (code, libelle, categorie_principale) VALUES
-- 31 PROFESSIONS LIBERALES
('311c', 'Chirurgiens-dentistes', 3),
('311d', 'Psychologues, psychanalystes, psychothérapeutes (non médecins)', 3),
('311e', 'Vétérinaires', 3),
('312a', 'Avocats', 3),

-- 33 CADRES DE LA FONCTION PUBLIQUE
('331a', 'Personnels de direction de la fonction publique (Etat, collectivités locales, hôpitaux)', 3),
('332a', 'Ingénieurs de l''Etat et assimilés', 3),
('332b', 'Ingénieurs des collectivités locales et des hôpitaux', 3),
('333c', 'Cadres de la Poste', 3),
('333d', 'Cadres administratifs de France Télécom (statut public)', 3),
('333e', 'Autres personnels administratifs de catégorie A de l''Etat et assimilés (hors Enseignement, Patrimoine)', 3),
('333f', 'Personnel administratif de catégorie A des collectivités locales et hôpitaux publics (hors Enseignement, Patrimoine)', 3),

-- 34 PROFESSEURS, PROFESSIONS SCIENTIFIQUES
('341a', 'Professeurs agrégés et certifiés de l''enseignement secondaire', 3),
('341b', 'Chefs d''établissement de l''enseignement secondaire et inspecteurs', 3),
('342b', 'Professeurs et maîtres de conférences', 3),
('342c', 'Professeurs agrégés et certifiés en fonction dans l''enseignement supérieur', 3),
('342d', 'Personnel enseignant temporaire de l''enseignement supérieur', 3),
('342f', 'Directeurs et chargés de recherche de la recherche publique', 3),
('342g', 'Ingénieurs d''étude et de recherche de la recherche publique', 3),
('342h', 'Allocataires de la recherche publique', 3),
('343a', 'Psychologues spécialistes de l''orientation scolaire et professionnelle', 3),
('344a', 'Médecins hospitaliers sans activité libérale', 3),
('344b', 'Médecins salariés non hospitaliers', 3),
('344c', 'Internes en médecine, odontologie et pharmacie', 3),
('344d', 'Pharmaciens salariés', 3),

-- 35 PROFESSIONS DE L'INFORMATION, DES ARTS ET DES SPECTACLES
('351a', 'Bibliothécaires, archivistes, conservateurs et autres cadres du patrimoine', 3),
('352a', 'Journalistes (y. c. rédacteurs en chef)', 3),
('352b', 'Auteurs littéraires, scénaristes, dialoguistes', 3),
('353a', 'Directeurs de journaux, administrateurs de presse, directeurs d''éditions (littéraire, musicale, audiovisuelle et multimédia)', 3),
('353b', 'Directeurs, responsables de programmation et de production de l''audiovisuel et des spectacles', 3),
('353c', 'Cadres artistiques et technico-artistiques de la réalisation de l''audiovisuel et des spectacles', 3),
('354a', 'Artistes plasticiens', 3),
('354b', 'Artistes de la musique et du chant', 3),
('354c', 'Artistes dramatiques', 3),
('354e', 'Artistes de la danse', 3),
('354f', 'Artistes du cirque et des spectacles divers', 3),
('354g', 'Professeurs d''art (hors établissements scolaires)', 3),

-- 37 CADRES ADMINISTRATIFS ET COMMERCIAUX D'ENTREPRISES
('371a', 'Cadres d''état-major administratifs, financiers, commerciaux des grandes entreprises', 3),
('372a', 'Cadres chargés d''études économiques, financières, commerciales', 3),
('372b', 'Cadres de l''organisation ou du contrôle des services administratifs et financiers', 3),
('372c', 'Cadres spécialistes des ressources humaines et du recrutement', 3),
('372d', 'Cadres spécialistes de la formation', 3),
('372e', 'Juristes', 3),
('372f', 'Cadres de la documentation, de l''archivage (hors fonction publique)', 3),
('373a', 'Cadres des services financiers ou comptables des grandes entreprises', 3),
('373b', 'Cadres des autres services administratifs des grandes entreprises', 3),
('373c', 'Cadres des services financiers ou comptables des petites et moyennes entreprises', 3),
('373d', 'Cadres des autres services administratifs des petites et moyennes entreprises', 3),
('374a', 'Cadres de l''exploitation des magasins de vente du commerce de détail', 3),
('374b', 'Chefs de produits, acheteurs du commerce et autres cadres de la mercatique', 3),
('374c', 'Cadres commerciaux des grandes entreprises (hors commerce de détail)', 3),
('374d', 'Cadres commerciaux des petites et moyennes entreprises (hors commerce de détail)', 3),
('375a', 'Cadres de la publicité', 3),
('375b', 'Cadres des relations publiques et de la communication', 3),
('376a', 'Cadres des marchés financiers', 3),
('376b', 'Cadres des opérations bancaires', 3),
('376c', 'Cadres commerciaux de la banque', 3),
('376d', 'Chefs d''établissements et responsables de l''exploitation bancaire', 3),
('376e', 'Cadres des services techniques des assurances', 3),
('376f', 'Cadres des services techniques des organismes de sécurité sociale et assimilés', 3),
('376g', 'Cadres de l''immobilier', 3),
('377a', 'Cadres de l''hôtellerie et de la restauration', 3),

-- 38 INGENIEURS ET CADRES TECHNIQUES D'ENTREPRISES
('380a', 'Directeurs techniques des grandes entreprises', 3),
('381b', 'Ingénieurs et cadres d''étude et développement de l''agriculture, la pêche, les eaux et forêts', 3),
('381c', 'Ingénieurs et cadres de production et d''exploitation de l''agriculture, la pêche, les eaux et forêts', 3),
('382a', 'Ingénieurs et cadres d''étude du bâtiment et des travaux publics', 3),
('382b', 'Architectes salariés', 3),
('382c', 'Ingénieurs, cadres de chantier et conducteurs de travaux (cadres) du bâtiment et des travaux publics', 3),
('382d', 'Ingénieurs et cadres technico-commerciaux en bâtiment, travaux publics', 3),
('383a', 'Ingénieurs et cadres d''étude, recherche et développement en électricité, électronique', 3),
('383b', 'Ingénieurs et cadres de fabrication en matériel électrique, électronique', 3),
('383c', 'Ingénieurs et cadres technico-commerciaux en matériel électrique ou électronique professionnel', 3),
('384a', 'Ingénieurs et cadres d''étude, recherche et développement en mécanique et travail des métaux', 3),
('384b', 'Ingénieurs et cadres de fabrication en mécanique et travail des métaux', 3),
('384c', 'Ingénieurs et cadres technico-commerciaux en matériel mécanique professionnel', 3),
('385a', 'Ingénieurs et cadres d''étude, recherche et développement des industries de transformation (agroalimentaire, chimie, métallurgie, matériaux lourds)', 3),
('385b', 'Ingénieurs et cadres de fabrication des industries de transformation (agroalimentaire, chimie, métallurgie, matériaux lourds)', 3),
('385c', 'Ingénieurs et cadres technico-commerciaux des industries de transformations (biens intermédiaires)', 3),
('386b', 'Ingénieurs et cadres d''étude, recherche et développement de la distribution d''énergie, eau', 3),
('386c', 'Ingénieurs et cadres d''étude, recherche et développement des autres industries (imprimerie, matériaux souples, ameublement et bois)', 3),
('386d', 'Ingénieurs et cadres de la production et de la distribution d''énergie, eau', 3),
('386e', 'Ingénieurs et cadres de fabrication des autres industries (imprimerie, matériaux souples, ameublement et bois)', 3),
('387a', 'Ingénieurs et cadres des achats et approvisionnements industriels', 3),
('387b', 'Ingénieurs et cadres de la logistique, du planning et de l''ordonnancement', 3),
('387c', 'Ingénieurs et cadres des méthodes de production', 3),
('387d', 'Ingénieurs et cadres du contrôle-qualité', 3),
('387e', 'Ingénieurs et cadres de la maintenance, de l''entretien et des travaux neufs', 3),
('387f', 'Ingénieurs et cadres techniques de l''environnement', 3),
('388a', 'Ingénieurs et cadres d''étude, recherche et développement en informatique', 3),
('388b', 'Ingénieurs et cadres d''administration, maintenance, support et services aux utilisateurs en informatique', 3),
('388c', 'Chefs de projets informatiques, responsables informatiques', 3),
('388d', 'Ingénieurs et cadres technico-commerciaux en informatique et télécommunications', 3),
('388e', 'Ingénieurs et cadres spécialistes des télécommunications', 3),
('389a', 'Ingénieurs et cadres techniques de l''exploitation des transports', 3),
('389b', 'Officiers et cadres navigants techniques et commerciaux de l''aviation civile', 3),
('389c', 'Officiers et cadres navigants techniques de la marine marchande', 3);

-- 4 PROFESSIONS INTERMEDIAIRES
INSERT INTO nomenclature_pcs_ese (code, libelle, categorie_principale) VALUES
-- 42 PROFESSEURS DES ECOLES, INSTITUTEURS
('421a', 'Instituteurs', 4),
('421b', 'Professeurs des écoles', 4),
('422a', 'Professeurs d''enseignement général des collèges', 4),
('422b', 'Professeurs de lycée professionnel', 4),
('422c', 'Maîtres auxiliaires et professeurs contractuels de l''enseignement secondaire', 4),
('422d', 'Conseillers principaux d''éducation', 4),
('422e', 'Surveillants et aides-éducateurs des établissements d''enseignement', 4),
('423a', 'Moniteurs d''école de conduite', 4),
('423b', 'Formateurs et animateurs de formation continue', 4),
('424a', 'Moniteurs et éducateurs sportifs, sportifs professionnels', 4),
('425a', 'Sous-bibliothécaires, cadres intermédiaires du patrimoine', 4),

-- 43 PROFESSIONS INTERMEDIAIRES DE LA SANTE ET DU TRAVAIL SOCIAL
('431a', 'Cadres infirmiers et assimilés', 4),
('431b', 'Infirmiers psychiatriques', 4),
('431c', 'Puéricultrices', 4),
('431d', 'Infirmiers spécialisés (autres qu''infirmiers psychiatriques et puéricultrices)', 4),
('431e', 'Sages-femmes', 4),
('431f', 'Infirmiers en soins généraux', 4),
('432b', 'Masseurs-kinésithérapeutes rééducateurs', 4),
('432d', 'Autres spécialistes de la rééducation', 4),
('433a', 'Techniciens médicaux', 4),
('433b', 'Opticiens lunetiers et audioprothésistes', 4),
('433c', 'Autres spécialistes de l''appareillage médical', 4),
('433d', 'Préparateurs en pharmacie', 4),
('434a', 'Cadres', 4),
('434b', 'Assistants de service social', 4),
('434c', 'Conseillers en économie sociale familiale', 4),
('434d', 'Educateurs spécialisés', 4),
('434e', 'Moniteurs éducateurs', 4),
('434f', 'Educateurs techniques spécialisés, moniteurs d''atelier', 4),
('434g', 'Educateurs de jeunes enfants', 4),
('435a', 'Directeurs de centres socioculturels et de loisirs', 4),
('435b', 'Animateurs socioculturels et de loisirs', 4),

-- 44 CLERGE, RELIGIEUX
('441a', 'Clergé séculier', 4),
('441b', 'Clergé régulier', 4),

-- 45 PROFESSIONS INTERMEDIAIRES ADMINISTRATIVES DE LA FONCTION PUBLIQUE
('451a', 'Professions intermédiaires de la Poste', 4),
('451b', 'Professions intermédiaires administratives de France Télécom (statut public)', 4),
('451e', 'Autres personnels administratifs de catégorie B de l''Etat et assimilés (hors Enseignement, Patrimoine)', 4),
('451g', 'Professions intermédiaires administratives des collectivités locales', 4),
('451h', 'Professions intermédiaires administratives des hôpitaux', 4),

-- 46 PROFESSIONS INTERMEDIAIRES ADMINISTRATIVES ET COMMERCIALES DES ENTREPRISES
('461b', 'Secrétaires de direction, assistants de direction (non cadres)', 4),
('461c', 'Secrétaires de niveau supérieur (non cadres, hors secrétaires de direction)', 4),
('461d', 'Maîtrise et techniciens des services financiers ou comptables', 4),
('461e', 'Maîtrise et techniciens administratifs des services juridiques ou du personnel', 4),
('461f', 'Maîtrise et techniciens administratifs des autres services administratifs', 4),
('462a', 'Chefs de petites surfaces de vente', 4),
('462b', 'Maîtrise de l''exploitation des magasins de vente', 4),
('462c', 'Acheteurs non classés cadres, aides-acheteurs', 4),
('462d', 'Animateurs commerciaux des magasins de vente, marchandiseurs (non cadres)', 4),
('462e', 'Autres professions intermédiaires commerciales (sauf techniciens des forces de vente)', 4),
('463a', 'Techniciens commerciaux et technico-commerciaux, représentants en informatique', 4),
('463b', 'Techniciens commerciaux et technico-commerciaux, représentants en biens d''équipement, en biens intermédiaires, commerce interindustriel (hors informatique)', 4),
('463c', 'Techniciens commerciaux et technico-commerciaux, représentants en biens de consommation auprès d''entreprises', 4),
('463d', 'Techniciens commerciaux et technico-commerciaux, représentants en services auprès d''entreprises ou de professionnels (hors banque, assurance, informatique)', 4),
('463e', 'Techniciens commerciaux et technico-commerciaux, représentants auprès de particuliers (hors banque, assurance, informatique)', 4),
('464a', 'Assistants de la publicité, des relations publiques', 4),
('464b', 'Interprètes, traducteurs', 4),
('465a', 'Concepteurs et assistants techniques des arts graphiques, de la mode et de la décoration', 4),
('465b', 'Assistants techniques de la réalisation des spectacles vivants et audiovisuels', 4),
('465c', 'Photographes', 4),
('466a', 'Responsables commerciaux et administratifs des transports de voyageurs et du tourisme (non cadres)', 4),
('466b', 'Responsables commerciaux et administratifs des transports de marchandises (non cadres)', 4),
('466c', 'Responsables d''exploitation des transports de voyageurs et de marchandises (non cadres)', 4),
('467a', 'Chargés de clientèle bancaire', 4),
('467b', 'Techniciens des opérations bancaires', 4),
('467c', 'Professions intermédiaires techniques et commerciales des assurances', 4),
('467d', 'Professions intermédiaires techniques des organismes de sécurité sociale', 4),
('468a', 'Maîtrise de restauration : salle et service', 4),
('468b', 'Maîtrise de l''hébergement : hall et étages', 4),

-- 47 TECHNICIENS (sauf techniciens tertiaires)
('471a', 'Techniciens d''étude et de conseil en agriculture, eaux et forêts', 4),
('471b', 'Techniciens d''exploitation et de contrôle de la production en agriculture, eaux et forêts', 4),
('472a', 'Dessinateurs en bâtiment, travaux publics', 4),
('472b', 'Géomètres, topographes', 4),
('472c', 'Métreurs et techniciens divers du bâtiment et des travaux publics', 4),
('472d', 'Techniciens des travaux publics de l''Etat et des collectivités locales', 4),
('473a', 'Dessinateurs en électricité, électromécanique et électronique', 4),
('473b', 'Techniciens de recherche-développement et des méthodes de fabrication en électricité, électromécanique et électronique', 4),
('473c', 'Techniciens de fabrication et de contrôle-qualité en électricité, électromécanique et électronique', 4),
('474a', 'Dessinateurs en construction mécanique et travail des métaux', 4),
('474b', 'Techniciens de recherche-développement et des méthodes de fabrication en construction mécanique et travail des métaux', 4),
('474c', 'Techniciens de fabrication et de contrôle-qualité en construction mécanique et travail des métaux', 4),
('475a', 'Techniciens de recherche-développement et des méthodes de production des industries de transformation', 4),
('475b', 'Techniciens de production et de contrôle-qualité des industries de transformation', 4),
('476a', 'Assistants techniques, techniciens de l''imprimerie et de l''édition', 4),
('476b', 'Techniciens de l''industrie des matériaux souples, de l''ameublement et du bois', 4),
('477a', 'Techniciens de la logistique, du planning et de l''ordonnancement', 4),
('477b', 'Techniciens d''installation et de maintenance des équipements industriels (électriques, électromécaniques, mécaniques, hors informatique)', 4),
('477c', 'Techniciens d''installation et de maintenance des équipements non industriels (hors informatique et télécommunications)', 4),
('477d', 'Techniciens de l''environnement et du traitement des pollutions', 4),
('478a', 'Techniciens d''étude et de développement en informatique', 4),
('478b', 'Techniciens de production, d''exploitation en informatique', 4),
('478c', 'Techniciens d''installation, de maintenance, support et services aux utilisateurs en informatique', 4),
('478d', 'Techniciens des télécommunications et de l''informatique des réseaux', 4),
('479a', 'Techniciens des laboratoires de recherche publique ou de l''enseignement', 4),
('479b', 'Experts de niveau technicien, techniciens divers', 4),

-- 48 CONTREMAITRES, AGENTS DE MAITRISE
('480a', 'Contremaîtres et agents d''encadrement (non cadres) en agriculture, sylviculture', 4),
('480b', 'Maîtres d''équipage de la marine marchande et de la pêche', 4),
('481a', 'Conducteurs de travaux (non cadres)', 4),
('481b', 'Chefs de chantier (non cadres)', 4),
('482a', 'Agents de maîtrise en fabrication de matériel électrique, électronique', 4),
('483a', 'Agents de maîtrise en construction mécanique, travail des métaux', 4),
('484a', 'Agents de maîtrise en fabrication : agroalimentaire, chimie, plasturgie, pharmacie', 4),
('484b', 'Agents de maîtrise en fabrication : métallurgie, matériaux lourds et autres industries de transformation', 4),
('485a', 'Agents de maîtrise et techniciens en production et distribution d''énergie, eau, chauffage', 4),
('485b', 'Agents de maîtrise en fabrication des autres industries (imprimerie, matériaux souples, ameublement et bois)', 4),
('486b', 'Agents de maîtrise en maintenance, installation en électricité et électronique', 4),
('486c', 'Agents de maîtrise en maintenance, installation en électromécanique', 4),
('486d', 'Agents de maîtrise en maintenance, installation en mécanique', 4),
('486e', 'Agents de maîtrise en entretien général, installation, travaux neufs (hors mécanique, électromécanique, électronique)', 4),
('487a', 'Responsables d''entrepôt, de magasinage', 4),
('487b', 'Responsables du tri, de l''emballage, de l''expédition et autres responsables de la manutention', 4),
('488a', 'Maîtrise de restauration : cuisine/production', 4),
('488b', 'Maîtrise de restauration : gestion d''établissement', 4);

-- 5 EMPLOYES
INSERT INTO nomenclature_pcs_ese (code, libelle, categorie_principale) VALUES
-- 52 EMPLOYES CIVILS ET AGENTS DE SERVICE DE LA FONCTION PUBLIQUE
('521a', 'Employés de la Poste', 5),
('521b', 'Employés de France Télécom (statut public)', 5),
('523b', 'Adjoints administratifs de l''Etat et assimilés (sauf Poste, France Télécom)', 5),
('523c', 'Adjoints administratifs des collectivités locales', 5),
('523d', 'Adjoints administratifs des hôpitaux publics', 5),
('524b', 'Agents administratifs de l''Etat et assimilés (sauf Poste, France Télécom)', 5),
('524c', 'Agents administratifs des collectivités locales', 5),
('524d', 'Agents administratifs des hôpitaux publics', 5),
('525a', 'Agents de service des établissements primaires', 5),
('525b', 'Agents de service des autres établissements d''enseignement', 5),
('525c', 'Agents de service de la fonction publique (sauf écoles, hôpitaux)', 5),
('525d', 'Agents de service hospitaliers', 5),
('526a', 'Aides-soignants', 5),
('526b', 'Assistants dentaires, médicaux et vétérinaires, aides de techniciens médicaux', 5),
('526c', 'Auxiliaires de puériculture', 5),
('526d', 'Aides médico-psychologiques', 5),
('526e', 'Ambulanciers', 5),

-- 53 AGENTS DE SURVEILLANCE
('533a', 'Pompiers', 5),
('533b', 'Agents techniques forestiers, gardes des espaces naturels', 5),
('533c', 'Agents de surveillance du patrimoine et des administrations', 5),
('534a', 'Agents civils de sécurité et de surveillance', 5),
('534b', 'Convoyeurs de fonds, gardes du corps, enquêteurs privés et métiers assimilés', 5),

-- 54 EMPLOYES ADMINISTRATIFS D'ENTREPRISE
('541b', 'Agents d''accueil qualifiés, hôtesses d''accueil et d''information', 5),
('541c', 'Agents d''accueil non qualifiés', 5),
('541d', 'Standardiste téléphonistes', 5),
('542a', 'Secrétaires', 5),
('542b', 'Dactylos, sténodactylos (sans secrétariat), opérateurs de traitement de texte', 5),
('543b', 'Employés qualifiés des services comptables ou financiers', 5),
('543c', 'Employés non qualifiés des services comptables ou financiers', 5),
('543e', 'Employés qualifiés des services du personnel et des services juridiques', 5),
('543f', 'Employés qualifiés des services commerciaux des entreprises (hors vente)', 5),
('543g', 'Employés administratifs qualifiés des autres services des entreprises', 5),
('543h', 'Employés administratifs non qualifiés', 5),
('544a', 'Employés et opérateurs d''exploitation en informatique', 5),
('545a', 'Employés administratifs des services techniques de la banque', 5),
('545b', 'Employés des services commerciaux de la banque', 5),
('545c', 'Employés des services techniques des assurances', 5),
('545d', 'Employés des services techniques des organismes de sécurité sociale et assimilés', 5),
('546a', 'Contrôleurs des transports (personnels roulants)', 5),
('546b', 'Agents des services commerciaux des transports de voyageurs et du tourisme', 5),
('546c', 'Employés administratifs d''exploitation des transports de marchandises', 5),
('546d', 'Hôtesses de l''air et stewards', 5),
('546e', 'Autres agents et hôtesses d''accompagnement (transports, tourisme)', 5),

-- 55 EMPLOYES DE COMMERCE
('551a', 'Employés de libre-service du commerce et magasiniers', 5),
('552a', 'Caissiers de magasin', 5),
('553b', 'Vendeurs polyvalents des grands magasins', 5),
('553c', 'Autres vendeurs non spécialisés', 5),
('554a', 'Vendeurs en alimentation', 5),
('554b', 'Vendeurs en ameublement, décor, équipement du foyer', 5),
('554c', 'Vendeurs en droguerie, bazar, quincaillerie, bricolage', 5),
('554d', 'Vendeurs du commerce de fleurs', 5),
('554e', 'Vendeurs en habillement et articles de sport', 5),
('554f', 'Vendeurs en produits de beauté, de luxe (hors biens culturels) et optique', 5),
('554g', 'Vendeurs de biens culturels (livres, disques, multimédia, objets d''art)', 5),
('554h', 'Vendeurs de tabac, presse et articles divers', 5),
('554j', 'Pompistes et gérants de station-service (salariés ou mandataires)', 5),
('555a', 'Vendeurs par correspondance, télévendeurs', 5),
('556a', 'Vendeurs en gros de biens d''équipement, biens intermédiaires', 5),

-- 56 PERSONNELS DES SERVICES DIRECTS AUX PARTICULIERS
('561b', 'Serveurs, commis de restaurant, garçons qualifiés', 5),
('561c', 'Serveurs, commis de restaurant, garçons non qualifiés', 5),
('561d', 'Aides de cuisine, apprentis de cuisine et employés polyvalents de la restauration', 5),
('561e', 'Employés de l''hôtellerie : réception et hall', 5),
('561f', 'Employés d''étage et employés polyvalents de l''hôtellerie', 5),
('562a', 'Manucures, esthéticiens', 5),
('562b', 'Coiffeurs', 5),
('563a', 'Assistantes maternelles, gardiennes d''enfants, familles d''accueil', 5),
('563b', 'Aides à domicile, aides ménagères, travailleuses familiales', 5),
('563c', 'Employés de maison et personnels de ménage chez des particuliers', 5),
('564a', 'Concierges, gardiens d''immeubles', 5),
('564b', 'Employés des services divers', 5);

-- 6 OUVRIERS
INSERT INTO nomenclature_pcs_ese (code, libelle, categorie_principale) VALUES
-- 62 OUVRIERS QUALIFIES DE TYPE INDUSTRIEL
('621a', 'Chefs d''équipe du gros œuvre et des travaux publics', 6),
('621b', 'Ouvriers qualifiés du travail du béton', 6),
('621c', 'Conducteurs qualifiés d''engins de chantiers du bâtiment et des travaux publics', 6),
('621d', 'Ouvriers des travaux publics en installations électriques et de télécommunications', 6),
('621e', 'Autres ouvriers qualifiés des travaux publics', 6),
('621f', 'Ouvriers qualifiés des travaux publics (salariés de l''Etat et des collectivités locales)', 6),
('621g', 'Mineurs de fond qualifiés et autres ouvriers qualifiés des industries d''extraction (carrières, pétrole, gaz...)', 6),
('622a', 'Opérateurs qualifiés sur machines automatiques en production électrique ou électronique', 6),
('622c', 'Monteurs câbleurs qualifiés en électricité', 6),
('622d', 'Câbleurs qualifiés en électronique (prototype, unité, petite série)', 6),
('622e', 'Autres monteurs câbleurs en électronique', 6),
('622f', 'Bobiniers qualifiés', 6),
('622g', 'Plate-formistes, contrôleurs qualifiés de matériel électrique ou électronique', 6),
('623a', 'Chaudronniers-tôliers industriels, opérateurs qualifiés du travail en forge, conducteurs qualifiés d''équipement de formage, traceurs qualifiés', 6),
('623b', 'Tuyauteurs industriels qualifiés', 6),
('623d', 'Opérateurs qualifiés sur machine de soudage', 6),
('623e', 'Soudeurs manuels', 6),
('623f', 'Opérateurs qualifiés d''usinage des métaux travaillant à l''unité ou en petite série, moulistes qualifiés', 6),
('623g', 'Opérateurs qualifiés d''usinage des métaux sur autres machines (sauf moulistes)', 6),
('624b', 'Monteurs, metteurs au point très qualifiés d''ensembles mécaniques travaillant à l''unité ou en petite série', 6),
('624c', 'Monteurs qualifiés d''ensembles mécaniques travaillant en moyenne ou en grande série', 6),
('624d', 'Monteurs qualifiés en structures métalliques', 6),
('624e', 'Ouvriers qualifiés de contrôle et d''essais en mécanique', 6),
('624f', 'Ouvriers qualifiés des traitements thermiques et de surface sur métaux', 6),
('624g', 'Autres mécaniciens ou ajusteurs qualifiés (ou spécialité non reconnue)', 6),
('625a', 'Pilotes d''installation lourde des industries de transformation : agroalimentaire, chimie, plasturgie, énergie', 6),
('625b', 'Ouvriers qualifiés et agents qualifiés de laboratoire : agroalimentaire, chimie, biologie, pharmacie', 6),
('625c', 'Autres opérateurs et ouvriers qualifiés de la chimie (y c. pharmacie) et de la plasturgie', 6),
('625d', 'Opérateurs de la transformation des viandes', 6),
('625f', 'Autres opérateurs travaillant sur installations ou machines : industrie agroalimentaire (hors transformation des viandes)', 6),
('625g', 'Autres ouvriers de production qualifiés ne travaillant pas sur machine : industrie agroalimentaire (hors transformation des viandes)', 6),
('625h', 'Ouvriers qualifiés des autres industries (eau, gaz, énergie, chauffage)', 6),
('626a', 'Pilotes d''installation lourde des industries de transformation : métallurgie, production verrière, matériaux de construction', 6),
('626b', 'Autres opérateurs et ouvriers qualifiés : métallurgie, production verrière, matériaux de construction', 6),
('626c', 'Opérateurs et ouvriers qualifiés des industries lourdes du bois et de la fabrication du papier-carton', 6),
('627a', 'Opérateurs qualifiés du textile et de la mégisserie', 6),
('627b', 'Ouvriers qualifiés de la coupe des vêtements et de l''habillement, autres opérateurs de confection qualifiés', 6),
('627c', 'Ouvriers qualifiés du travail industriel du cuir', 6),
('627d', 'Ouvriers qualifiés de scierie, de la menuiserie industrielle et de l''ameublement', 6),
('627e', 'Ouvriers de la photogravure et des laboratoires photographiques et cinématographiques', 6),
('627f', 'Ouvriers de la composition et de l''impression, ouvriers qualifiés de la brochure, de la reliure et du façonnage du papier-carton', 6),
('628a', 'Mécaniciens qualifiés de maintenance, entretien : équipements industriels', 6),
('628b', 'Electromécaniciens, électriciens qualifiés d''entretien : équipements industriels', 6),
('628c', 'Régleurs qualifiés d''équipement de fabrication (travail des métaux, mécanique)', 6),
('628d', 'Régleurs qualifiés d''équipement de fabrication (hors travail des métaux et mécanique)', 6),
('628e', 'Ouvriers qualifiés de l''assainissement et du traitement des déchets', 6),
('628f', 'Agents qualifiés de laboratoire (sauf chimie, santé)', 6),
('628g', 'Ouvriers qualifiés divers de type industriel', 6),

-- 63 OUVRIERS QUALIFIES DE TYPE ARTISANAL
('631a', 'Jardiniers', 6),
('632a', 'Maçons qualifiés', 6),
('632b', 'Ouvriers qualifiés du travail de la pierre', 6),
('632c', 'Charpentiers en bois qualifiés', 6),
('632d', 'Menuisiers qualifiés du bâtiment', 6),
('632e', 'Couvreurs qualifiés', 6),
('632f', 'Plombiers et chauffagistes qualifiés', 6),
('632g', 'Peintres et ouvriers qualifiés de pose de revêtements sur supports verticaux', 6),
('632h', 'Soliers moquetteurs et ouvriers qualifiés de pose de revêtements souples sur supports horizontaux', 6),
('632j', 'Monteurs qualifiés en agencement, isolation', 6),
('632k', 'Ouvriers qualifiés d''entretien général des bâtiments', 6),
('633a', 'Electriciens qualifiés de type artisanal (y c. bâtiment)', 6),
('633b', 'Dépanneurs qualifiés en radiotélévision, électroménager, matériel électronique', 6),
('633c', 'Electriciens, électroniciens qualifiés en maintenance entretien, réparation : automobile', 6),
('633d', 'Electriciens, électroniciens qualifiés en maintenance, entretien : équipements non industriels', 6),
('634a', 'Carrossiers d''automobiles qualifiés', 6),
('634b', 'Métalliers, serruriers qualifiés', 6),
('634c', 'Mécaniciens qualifiés en maintenance, entretien, réparation : automobile', 6),
('634d', 'Mécaniciens qualifiés de maintenance, entretien : équipements non industriels', 6),
('635a', 'Tailleurs et couturières qualifiés, ouvriers qualifiés du travail des étoffes (sauf fabrication de vêtements), ouvriers qualifiés de type artisanal du travail du cuir', 6),
('636a', 'Bouchers (sauf industrie de la viande)', 6),
('636b', 'Charcutiers (sauf industrie de la viande)', 6),
('636c', 'Boulangers, pâtissiers (sauf activité industrielle)', 6),
('636d', 'Cuisiniers et commis de cuisine', 6),
('637a', 'Modeleurs (sauf modeleurs de métal), mouleurs-noyauteurs à la main, ouvriers qualifiés du travail du verre ou de la céramique à la main', 6),
('637b', 'Ouvriers d''art', 6),
('637c', 'Ouvriers et techniciens des spectacles vivants et audiovisuels', 6),
('637d', 'Ouvriers qualifiés divers de type artisanal', 6),

-- 64 CHAUFFEURS
('641a', 'Conducteurs routiers et grands routiers', 6),
('641b', 'Conducteurs de véhicule routier de transport en commun', 6),
('642a', 'Conducteurs de taxi', 6),
('642b', 'Conducteurs de voiture particulière', 6),
('643a', 'Conducteurs livreurs, coursiers', 6),
('644a', 'Conducteurs de véhicule de ramassage des ordures ménagères', 6),

-- 65 OUVRIERS QUALIFIES DE LA MANUTENTION, DU MAGASINAGE ET DU TRANSPORT
('651a', 'Conducteurs d''engin lourd de levage', 6),
('651b', 'Conducteurs d''engin lourd de manœuvre', 6),
('652a', 'Ouvriers qualifiés de la manutention, conducteurs de chariots élévateurs, caristes', 6),
('652b', 'Dockers', 6),
('653a', 'Magasiniers qualifiés', 6),
('654b', 'Conducteurs qualifiés d''engins de transport guidés (sauf remontées mécaniques)', 6),
('654c', 'Conducteurs qualifiés de systèmes de remontées mécaniques', 6),
('655a', 'Autres agents et ouvriers qualifiés (sédentaires) des services d''exploitation des Transports', 6),
('656b', 'Matelots de la marine marchande', 6),
('656c', 'Capitaines et matelots timoniers de la navigation fluviale', 6),

-- 67 OUVRIERS NON QUALIFIES DE TYPE INDUSTRIEL
('671a', 'Ouvriers non qualifiés des travaux publics de l''Etat et des collectivités locales', 6),
('671c', 'Ouvriers non qualifiés des travaux publics et du travail du béton', 6),
('671d', 'Aides-mineurs, ouvriers non qualifiés de l''extraction', 6),
('672a', 'Ouvriers non qualifiés de l''électricité et de l''électronique', 6),
('673a', 'Ouvriers de production non qualifiés travaillant par enlèvement de métal', 6),
('673b', 'Ouvriers de production non qualifiés travaillant par formage de métal', 6),
('673c', 'Ouvriers non qualifiés de montage, contrôle en mécanique et travail des métaux', 6),
('674a', 'Ouvriers de production non qualifiés : chimie, pharmacie, plasturgie', 6),
('674b', 'Ouvriers de production non qualifiés de la transformation des viandes', 6),
('674c', 'Autres ouvriers de production non qualifiés : industrie agroalimentaire', 6),
('674d', 'Ouvriers de production non qualifiés : métallurgie, production verrière, céramique, matériaux de construction', 6),
('674e', 'Ouvriers de production non qualifiés : industrie lourde du bois, fabrication des papiers et cartons', 6),
('675a', 'Ouvriers de production non qualifiés du textile et de la confection, de la tannerie-mégisserie et du travail du cuir', 6),
('675b', 'Ouvriers de production non qualifiés du travail du bois et de l''ameublement', 6),
('675c', 'Ouvriers de production non qualifiés de l''imprimerie, presse, édition', 6),
('676a', 'Manutentionnaires non qualifiés', 6),
('676b', 'Déménageurs (hors chauffeurs-déménageurs), non qualifiés', 6),
('676c', 'Ouvriers du tri, de l''emballage, de l''expédition, non qualifiés', 6),
('676d', 'Agents non qualifiés des services d''exploitation des transports', 6),
('676e', 'Ouvriers non qualifiés divers de type industriel', 6),

-- 68 OUVRIERS NON QUALIFIES DE TYPE ARTISANAL
('681a', 'Ouvriers non qualifiés du gros œuvre du bâtiment', 6),
('681b', 'Ouvriers non qualifiés du second œuvre du bâtiment', 6),
('682a', 'Métalliers, serruriers, réparateurs en mécanique non qualifiés', 6),
('683a', 'Apprentis boulangers, bouchers, charcutiers', 6),
('684a', 'Nettoyeurs', 6),
('684b', 'Ouvriers non qualifiés de l''assainissement et du traitement des déchets', 6),
('685a', 'Ouvriers non qualifiés divers de type artisanal', 6),

-- 69 OUVRIERS AGRICOLES ET ASSIMILES
('691a', 'Conducteurs d''engin agricole ou forestier', 6),
('691b', 'Ouvriers de l''élevage', 6),
('691c', 'Ouvriers du maraîchage ou de l''horticulture', 6),
('691d', 'Ouvriers de la viticulture ou de l''arboriculture fruitière', 6),
('691e', 'Ouvriers agricoles sans spécialisation particulière', 6),
('691f', 'Ouvriers de l''exploitation forestière ou de la sylviculture', 6),
('692a', 'Marins-pêcheurs et ouvriers de l''aquaculture', 6);
